export const BRIEF_PROMPT_VERSION = 'brief-v4';
export const BRIEF_GEMINI_TIMEOUT_MS = 45_000;
export const BRIEF_MAX_SECTION_LENGTH = 2_000;
export const BRIEF_MAX_STANCE_RATIONALE_LENGTH = 1_500;
export const BRIEF_MAX_HOLDING_NOTES_LENGTH = 500;
export const BRIEF_MAX_OUTPUT_TOKENS = 2_560;
export const BRIEF_TICKER_PATTERN = /^[A-Z][A-Z0-9.-]{0,11}$/;
